Logical: DosagingTJT
Title: "Dosaging TJT - logical model"
Description: "Instructions about requested administration of the product."

* sequence 0..1 INT "Order of the dosage instruction, in case one treatment consists of several dosaging schemes." "Ravimi manustamise järjekord."
* text 0..1 ST "Free text usage/dosage instructions." "Tekstiline annustamise juhend."
* patientInstruction 0..1 ST "Patient oriented instructions as free text." "Patsiendile mõeldud juhend. Keerulise annustamisskeemi puhul lisa juhend"
* additionalInstruction 0..* CD "Coded instructions, e.g warnings to the patient, like 'may cause drowsiness' etc" "Hoiatus, näiteks võib teha uimaseks või kodeeritud juhend."
* doseAndRate 0..* Class "Amount of medication administered per one dose (one timing)." "Ravimi annus ühe manustamise kohta või kõige sagedamini kasutatav annustamisjuhend."
  * type 0..1 CD "The kind of dose or rate specified e.g calculated, ordered, etc." "Annuse ja manustamise kiiruse tüüp, näiteks tellitud, kalkuleeritud."
  * dose 0..1 PQ "Amount of medication per one dose e.g 1 tablet, 1-2 tablets, 100 ml." "Ravimi kogus ühe annuse kohta."
  * rate 0..1 RTO "Amount of medication per unit of time. Time period during which one defined dose is administered e.g per 1 hour, per 5-10 minutes." "Periood, mille jooksul ühte ravimi annust ravimit manustatakse."
* timing 0..1 Class "When medication should be administered e.g period, time of day, frequency, etc." "Manustamise aeg, võib olla periood, sagedus, aeg jne."
  * event 0..* DT "Exact date and/or time of the administration." "Täpne manustamise aeg."
  * code 0..1 CD "Timing abbreviation, e.g AM - morning." "Annustamise ajaühikute lühendid, näiteks AM - hommik, BID - kaks korda päevas."
  * repeat 0..1 Class "Repetition of the administration." "Manustamise kordused."
    * bounds 0..1 Class "Time bounds for the treatment (current dosaging scheme)." "Piirid, mis on seotud  ravimi manustamise ajalise pikkusega/pikkusvahemik või alguse ja/või lõpuga."
      * duration 0..1 PQ "Number of time units, e.g 10 days." "Ravimi annustamise kestvus, näiteks 5 päeva."
      * range 0..1 Class "A range of numbers of time units, e.g 5-10 days." "Mis aja jooksul ravimit annustatakse, näiteks 2-6 päeva."
        * rangeMinimum 0..1 PQ "Minimum number of time units." "Minimaalne ravimi annustamise ajaühik, näiteks 5 päeva"
        * rangeMaximum 0..1 PQ "Maximum number of time units." "Maximaalne ravimi annustamise ajaühik, näiteks 10 päeva."
      * period 0..1 Class "Start and end date, 12.04.2024 - 12.06.2024." "Ajavahemik (kuupäevaliselt), mille jooksul ravimit manustatakse, näiteks 12.04.2024 - 12.06.2024"
        * startDate 0..1 DT "Start date of administering medication." "Ravimi manustamise algus kuupäevaliselt."
        * endDate 0..1 DT "End time of administering medication." "Ravimi manustamise lõpp kuupäevaliselt."
    * count 0..1 Class "Number of times to repeat, exact or range." "Kordused"
      * count 1..1 INT "Number of times e.g twice, 10 times." "Mitu korda ravimit annustatakse, näiteks 2 korda, 7 korda."
      * countMax 0..1 INT "Maximum number of times e.g maximum 15 times." "Maksimaalne korduste aeg, näiteks maksimaalselt 15 korda."
    * duration 0..1 Class "Duration of one administration, exact or range." "Ravimi manustamise, annustamise kestvus kas täpne või ulatus (max)."
      * duration 1..1 PQ "Duration of administration e.g 15 minutes, 2 hour." "Kui pika aja jooksul ravimit annustatakse ja ühik, näiteks 15 minuti jooksul, 2 tunni jooksul."
      * durationMax 0..1 PQ "Maximum duration of administration e.g maximum 20 minutes." "Maksimaalne ravimi annustamise kestvus ja ühik, maksimaalselt 20 minuti jooksul"
    * frequency 0..1 Class "Frequency of intake/administration e.g 4 times a day." "Korduste arvu perioodi jooksul, näiteks neli korda päevas."
      * numberOfTimes 1..1 INT "Number of times per period e.g 8 times." "Annustamiste arv perioodi jooksul, näiteks 8 korda."
      * maxNumberOfTimes 0..1 INT "Maximum number of times per period e.g. maximum 8 times." "Maksimaalne korduste arv perioodi jooksul, näiteks maksimaalselt 8 korda."
      * period 1..1 PQ "Duration to which the frequency applies e.g '... / 1 day." "Kui sagedasti annustatakse ja ühik, näiteks .../ 1 päev."
      * periodMax 0..1 PQ "Upper limit of the period e.g 4-6 hours." "Periood kahe annustamise vahel, kui tihti võib ravimit manustada, näiteks manustada iga 4-6 tunni tagant."
    * dayOfWeek 0..* CD "The day of the week of administration, e.g Mon, Tue, etc." "Nädalapäev, millal päevadel manustatakse."
    * timeOfDay 0..* DT "Time of day of administration e.g 15:00." "Kellaaeg, millal manustatakse, näiteks kell 15.00."
    * eventTime 0..* Class "An event the administration is bound to, e.g before meal, 30 min before meal." "Tegevusega seotud manustamine, pool tundi enne sööki."
      * when 0..* CD "Time period or event e.g before meal, morning." "Millal manustada, näiteks hommikul, õhtul, enne sööki jne."
      * offset 0..1 INT "Minutes from event, before or after." "Mis periood (numbriliselt) ja ajaühik annustamisega seotud tegevuses, näiteks 30 min enne hommikusööki."
* asNeeded 0..1 BL "Take as needed." "Ravimi manustamine vajadusel."
* asNeededFor 0..* CD "Take as needed for the coded reason." "Ravimi manustamine vajadusel teatud juhul."
* bodySite 0..1 CD "Body site of administration." "Kehapiirkond, kuhu manustatakse."
* routeOfAdministration 0..1 CD "Route of administration." "Manustamisviis, manustamistee."
* methodOfAdministration 0..1 CD "Method or technique for administering medication." "Ravimi manustamise tehnika/meetod."
* maxDose 0..* Class "Maximum dose for the patient" "Maksimaalsed annused ajaühikus, elu jooksul ja ühe annuse kohta."
  * maxDosePerPeriod 0..* RTO "Upper limit on medication per unit of time" "Ravimite ülempiir ajaühiku kohta. Ravimi maksimaalne annus ühes/antud perioodis."
  * maxDosePerAdministration 0..1 PQ "Upper limit on medication per one administration" "Ravimite ülempiir manustamise kohta. Ravimi maksimaalne annus ühe manustamise/annustamise kohta."
  * maxDosePerLifetime 0..1 PQ "Upper limit on medication per lifetime of the patient" "Ravimite ülempiir patsiendi elu jooksul. Ravimi maksimaalne annus patsiendi eluaja jooksul."
   
