Logical: DosagingTJT
Title: "Dosaging TJT - logical model"
Description: "Instructions about requested administration of the product."

* sequence 0..1 INT "Order of the dosage instruction, in case one treatment consists of several dosaging schemes." "Ravimi annustamise järjekord."
* text 0..1 ST "Free text usage/dosage instructions." "Tekstiline juhis."
* additionalInstruction 0..* CD "Coded instructions, e.g warnings to the patient, like 'may cause drowsiness' etc" "Lisajuhis, valmistamisjuhis."
* patientInstruction 0..1 ST "Patient oriented instructions as free text." "Patsiendile mõeldud juhis."
* doseAndRate 0..* Class "Amount of medication administered per one dose (one timing). Amount of medication administered, to be administered or typical amount to be administered." "Annus ja kiirus."
  * type 0..1 CD "The kind of dose or rate specified (e.g calculated, ordered, etc)." "Annuse ja annustamise kiiruse tüüp- tellitud, kalkuleeritud."
  * dose 0..1 PQ "Amount of medication per one dose (1 tablet, 2-3 tablets, 50 ml)." "Ravimi kogus ühe annustamise kohta."
  * rate 0..1 RTO "Amount of medication per unit of time. Time period during which one defined dose is administered (per 1 hour, per 5-10 minutes.)" "Periood, mille jooksul ravimit manustatakse."
* timing 0..1 Class "When medication should be administered (period, time of day, frequency, etc)." "Annustamise aeg."
  * event 0..* DT "Exact date and/or time of the administration." "Täpne annustamise aeg."
  * code 0..1 CD "Timing abbreviation (AM - morning, Q4H - once in every 4 hours, BID - twice a day, etc)" "Annustamise skeemi ajaühiku lühendid."
  * repeat 0..1 Class "Repetition of the administration." "Manustamise kordused."
    * bounds 0..1 Class "Time bounds for the treatment (current dosaging scheme). (Only one of the following can exist.)" "Piirid, mis on seotud  ravimi annustamise ajalise pikkusega/pikkusvahemik või alguse ja/või lõpuga."
      * duration 0..1 PQ "Number of time units, e.g 10 days" "Ravimi annustamise kestvus, näiteks 5 päeva."
      * range 0..1 Class "A range of numbers of time units, 5-10 days." "Mis aja jooksul ravimit annustatakse, näiteks 2-6 päeva."
        * rangeMinimum 0..1 PQ "Minimum number of time units." "Minimaalne ravimi manustamise ajaühik. Näiteks 5 päeva"
        * rangeMaximum 0..1 PQ "Maximum number of time units." "Maximaalne ravimi manustamise ajaühik. Näiteks 10 päeva."
      * period 0..1 Class "Start and end date, 05.08.2023 - 10.08.2023" "Ajavahemik (kuupäevaliselt), mille jooksul ravimit annustatakse."
        * startDate 0..1 DT "Start date of administering medication." "Ravimi manustamise algus kuupäevaliselt."
        * endDate 0..1 DT "End time of administering medication." "Ravimi manustamise lõpp kuupäevaliselt."
    * count 0..1 Class "Number of times to repeat, exact or range" "Kordused"
      * count 1..1 INT "Number of times (e.g 'once', '10 times')" "Mitu korda ravimit annustatakse, näiteks 1 kord, 7 korda."
      * countMax 0..1 INT "Maximum number of times (e.g 'maximum 10 times')" "Maksimaalne korduste aeg. näiteks maksimaalselt 7 korda."
    * duration 0..1 Class "Duration of one administration, exact or range" " Ravimi annustamise kestvus."
      * duration 1..1 PQ "Duration of administration (e.g '5 minutes', '1 hour')" "Kui pika aja jooksul ravimit annustatakse ja ühik, näiteks 10 minuti jooksul, 1 h jooksul."
      * durationMax 0..1 PQ "Maximum duration of administration (e.g 'maximum 15 minutes')" "Maksimaalne ravimi annustamise kestvus ja ühik, maksimaalselt 15 minutit"
    * frequency 0..1 Class "Frequency of intake/administration (e.g 'three times a day')" "Korduste arvu perioodi jooksul, näiteks kolm korda päevas."
      * numberOfTimes 1..1 INT "Number of times per period (e.g '3 times')" "Annustamiste arv perioodi jooksul"
      * maxNumberOfTimes 0..1 INT "Maximum number of times per period (e.g. 'maximum 3 times')" "Maksimaalne korduste arv perioodi jooksul"
      * period 1..1 PQ "Duration to which the frequency applies (e.g '... / 1 day')" "Kui sagedasti annustatakse ja ühik"
      * periodMax 0..1 PQ "Upper limit of the period ( 4-6 hours)" "Periood kahe annustamise vahel, kui tihti võib ravimit manustada, näiteks manustada iga 4-6 tunni tagant."
    * dayOfWeek 0..* CD "The day of the week of administration, e.g Mon, Tue, etc" "Nädalapäev. Mis päevadel annustatakse"
    * timeOfDay 0..* DT "Time of day of administration (e.g '10:00')" "Päeva osa. Mis päeva osas annustatakse, näiteks lõina, kell 15.00."
    * eventTime 0..* Class "An event the administration is bound to, e.g 'before meal', '30 min before meal'" "Tegevusega seotud manustamine, pool tundi enne sööki."
      * when 0..* CD "Time period or event ('before meal', 'immediately', 'morning')" "Annustamisega seotud tegevus, näiteks tühja kõhuga hommikul."
      * offset 0..1 INT "Minutes from event, before or after" "Mis periood ja ajaühik annustamisega seotud tegevuses, näiteks 30 min enne hommikusööki."
* asNeeded 0..1 BL "Take as needed" "Ravimi manustamine vajadusel."
* asNeededFor 0..* CD "Take as needed for the coded reason" "Ravimi manustamine vajadusel teatud juhul."
* bodySite 0..1 CD "Body site of administration" "Kehapiirkond, kuhu manustatakse."
* routeOfAdministration 0..1 CD "Route of administration" "Manustamisviis, manustamistee."
* methodOfAdministration 0..1 CD "Method or technique for administering medication." "Ravimi manustamise tehnika/meetod."
* maxDose 0..* Class "Maximum dose for the patient" "Maksimaalsed annused ajaühikus, elu jooksul ja ühe annuse kohta."
  * maxDosePerPeriod 0..* RTO "Upper limit on medication per unit of time" "Ravimite ülempiir ajaühiku kohta. Ravimi maksimaalne annus ühes/antud perioodis"
  * maxDosePerAdministration 0..1 PQ "Upper limit on medication per one administration" "Ravimite ülempiir manustamise kohta. Ravimi maksimaalne annus ühe manustamise/annustamise kohta."
  * maxDosePerLifetime 0..1 PQ "Upper limit on medication per lifetime of the patient" "Ravimite ülempiir patsiendi elu jooksul. Ravimi maksimaalne annus patsiendi eluaja jooksul."
   