Logical: EHNprescription
Parent: Element
Id: EHNprescription
Description: "Dataset section from eHN ePrescription and eDispensation guidelines (as is)"
* ^url = "http://fhir.ee/StructureDefinition/eHNPrescription"
* patientAdministrativeData 0..* BackboneElement "A1.1. Patient administrative data" "A1.1. Patient administrative data"
  * familyName 0..* string "A.1.1.1 Family name/surname" "The family name/surname/last name of the patient [ISO TS 22220:2011]. This field can contain more than one element or multiple data elements could be present."
  * givenName 0..* string "A.1.1.2 Given name" "The given name/first name of the patient (also known as forename or first name) [ISO TS 22220:2011]. This field can contain more than one element."
  * dateOfBirth 0..* dateTime "A.1.1.3 Date of birth" "The date of birth of the patient [ISO TS 22220:2011]. This field may contain only the year if the day and month are not available, e.g.: 2009. Preferred CodeSystem: ISO 8601."
  * personalIdentifier 0..* string "A.1.1.4 Personal identifier" "Country ID, unique to the patient in that country. Example: ID for a Portuguese patient, national healthcare patient ID. Multiple identifiers could be provided."
  * gender 0..* CodeableConcept "A.1.1.5 Gender" "This field must contain a recognised valid value for 'administrative gender'. If different, "physiological sex" could be communicated elsewhere. Preferred CodeSystem: HL7 Administrative Gender"
  * nativeLanguage 0..* CodeableConcept "A.1.1.6 Native language" "The native language of the patient. This may be important for the information that is given to the patient regarding use of the prescribed product [N1228 ISO NP TS 17251]. Preferred CodeSystem: ISO 639."
* authenticationOfPrescription 0..* BackboneElement "A.1.2 Authentication of the prescription" "A.1.2 Authentication of the prescription"
  * identifierOfPrescription 0..* Identifier "A.1.2.1 Identifier of the Prescription" "A.1.2.1 Identifier of the Prescription"
  * issueDate 0..* string "A.1.2.2 Issue date" "A.1.2.2 Issue date"
* identificationOfPrescribingProfessional 0..* BackboneElement "A.1.3 Identification of the prescribing health professional" "A.1.3 Identification of the prescribing health professional"
  * familyName 0..* string "A.1.3.1 Family name" "A.1.3.1 Family name"
  * givenName 0..* string "A.1.3.2 Given name" "A.1.3.2 Given name"
  * professionalQualifications 0..* string "A.1.3.3 Professional qualifications" "A.1.3.3 Professional qualifications"
  * detailsForDirectContact 0..* string "A.1.3.4 Details for direct contact" "A.1.3.4 Details for direct contact"
  * workAddress 0..* string "A.1.3.5 Work address" "A.1.3.5 Work address"
  * signature 0..* string "A.1.3.6 Signature" "A.1.3.6 Signature"
  * healthcareProviderIdentifier 0..* string "A.1.3.7 Health care provider identifier" "A.1.3.7 Health care provider identifier"
* identificationOfPrescribedProduct 0..* BackboneElement "A1.4 Identification of the prescribed product" "A1.4 Identification of the prescribed product"
  * nameOfMedicinalProduct 0..* string "A.1.4.1 Name of the medicinal product" "A.1.4.1 Name of the medicinal product"
  * identifierOfMedicinalProduct 0..* BackboneElement "A.1.4.2 Identifier of the medicinal product" "A.1.4.2 Identifier of the medicinal product"
    * identifierOfPharmaceuticalProduct 0..* string "A.1.4.2.1 Identifier(s) of the pharmaceutical product" "A.1.4.2.1 Identifier(s) of the pharmaceutical product"
    * identifierOfPackagedMedicinalProduct 0..* string "A.1.4.2.2 Identifier(s) of the packaged medicinal product" "A.1.4.2.2 Identifier(s) of the packaged medicinal product"
  * marketingAuthorisationHolder 0..* string "A.1.4.3 Marketing authorisation holder" "A.1.4.3 Marketing authorisation holder"
  * activeSubstances 0..* BackboneElement "A.1.4.4 Active substance(s)" "A.1.4.4 Active substance(s)"
    * strengthOfActiveSubstances 0..* string "A.1.4.4.1 Strength of the active substance(s)" "A.1.4.4.1 Strength of the active substance(s)"
  * productClassification 0..* string "A.1.4.5 Product classification" "A.1.4.5 Product classification"
  * pharmaceuticalDoseForm 0..* string "A.1.4.6 Pharmaceutical dose form(s)" "A.1.4.6 Pharmaceutical dose form(s)"
  * unitOfPresentation 0..* string "A.1.4.7 Unit of presentation(s)" "A.1.4.7 Unit of presentation(s)"
  * packageType 0..* string "A.1.4.8 Package type" "A.1.4.8 Package type"
  * packSize 0..* string "A.1.4.9 Pack size" "A.1.4.9 Pack size"
* prescriptionInformation 0..* BackboneElement "A.1.5 Prescription information" "A.1.5 Prescription information"
  * quantityOfPrescribedProduct 0..* string "A.1.5.2 Quantity of prescribed product" "A.1.5.2 Quantity of prescribed product"
  * doseRegimen 0..* BackboneElement "A.1.5.3 Dose regimen" "A.1.5.3 Dose regimen"
    * numberOfUnitsPerIntake 0..* string "A.1.5.3.1 Number of units per intake" "A.1.5.3.1 Number of units per intake"
    * frequencyOfIntakes 0..* string "A.1.5.3.2 Frequency of intakes" "A.1.5.3.2 Frequency of intakes"
  * routeOfAdministration 0..* string "A.1.5.4 Route of administration" "A.1.5.4 Route of administration"
  * durationOfTreatment 0..* string "A.1.5.5 Duration of treatment" "A.1.5.5 Duration of treatment"
  * startingDateOfTherapy 0..* string "A.1.5.6 Starting date of therapy" "A.1.5.6 Starting date of therapy"
  * directionsForUse 0..* string "A.1.5.7 Directions for use" "A.1.5.7 Directions for use"
  * prescriptionExpiryDate 0..* string "A.1.5.8 Prescription expiry date" "A.1.5.8 Prescription expiry date"
  * repeats 0..* string "A.1.5.9 Repeats" "A.1.5.9 Repeats"
  * reasonForPrescription 0..* string "A.1.5.10 Reason for prescription" "A.1.5.10 Reason for prescription"
  * substitution 0..* string "A.1.5.11 Substitution" "A.1.5.11 Substitution"