Logical: MedicationTreatmentLineTJT
Title: "Medication TreatmentLine TJT - logical model"
Description: "A model for representing a Medication Treatment Line."
* identifier 0..* II "Unique business identifier(s) for the medication treatment line. Identifiers associated with this Medication Statement that are defined by business processes " "Ravimiskeemi rea universaalne identifikaator" 
* medication 1..1 Reference(MedicationTJT) "Medicinal product for which the treatment line refers to." "Ravim, mis on reaga seotud."
* status 1..1 CD "A code representing the status of recording the medication statement, recorded or draft." "Ravimiskeemi rea staatus. Kinnitatud-recorded, kinnitamata-draft."
* medicationOverview 1..1 Reference(MedicationOverviewTJT) "A model for the whole medication overview." "Ravimiskeem"
* verificationInformation 0..* Class "Verification of full overview. The overview is verified as a whole, but each lines is equipped with the information" "Ravimiskeemi kinnitamine, ravimiskeemi rea kinnitamisel kinnitatakse ka ravimiskeem" 
  * practitioner 1..1 Reference(PractitionerTJT) "HCP (or device, if authorized) verifying the treatments/overview" "Tervishoiutöötaja, kes kinnitas ravimiskeemi."  
  * verificationTime 1..1 DT "The date and time when this medication treatment line was verified" "Kinnitamise aeg"
// medicationTreatment 0..* Reference(MedicationTreatment) "Reference or identifier of grouper of lines that belong together, lines are parts of the same treatment" "Viide või identifikaator, mis grupeerib ravimid"
* derivedFrom 0..* II "Prescriptions that are connected to this Medication Treatment Line" "Seotud retseptid, siin on näiteks retsepti numbrid"
* indication 0..* CD "Reason why the product has been prescribed to the patient, or why the patient claims to be taking it" "Diagnoos või põhjus, miks patsient ravimit võtab"
* indicationText 0..1 ST "Additional instructions" "Lisa tekst, miks ravimit võetakse."
* dosageInstructions 0..* Reference(DosagingTJT) "Instructions about requested administration of the product" "Annustamisjuhis"
// preparationInstructions 0..* ST "Additional instructions about preparation or dispense." "Lisakommentaar valmistamise kohta."
* comment 0..* Class "Comment on the individual line" "Ravimiskeemi rea kommentaar."
  * author 1..1 Reference(PractitionerTJT) "Author of the comment (Pharmacist, doctor, social carer)." "Kommentaari autor."
  * date 1..1 DT "Time of comment" "Kommentaari aeg"
  * commentText 1..1 ST "Content of the comment" "Kommentaari sisu"
* recordingMetadata 1..1 Class "Metadata about reporting/authoring of the treatment line" "Info ravimiskeemi rea koostaja/koostamise kohta."
  * recorder 1..1 Reference(PractitionerTJT) "Person authoring/cancelling the treatment line, either by requesting a treatment or documenting a patient's statement. Typically a doctor, nurse, or pharmacist, or patient..." "Isik, kes ravimiskeemi rea koostas, raporteeris infot, tervishoiutöötaja, patsient jne."
  * recordedTime 1..1 DT "Time of creation of the treatment line" "Rea koostamise aeg."
  * patientReported 0..1 BL "The treatment line has been documented according to patient's." "Kas ravimiskeemi rea raporteerija on patsient."
  * authorResponsible 0..1 Reference(PractitionerTJT) "HCP who takes the clinical decision for the medication treatment line."  "Ravimiskeemi rea sisestaja."
  * authoringTime 0..1 DT "The time the decision was made." "Aeg, millal ravimiskeemi rida sisestati"
 
* informationSource 0..* Class "Initial author of the MedicationStatement." "Ravimiskeemi rea põhjus, immuniseerimine, retsept, ravimi väljastamine, "
  * initialAuthor 0..* Reference(PractitionerTJT) "Initial author of the medication schema line." "Ravimiskeemi rea algne koostaja."
  // relatedRequest 0..* Reference "Prescriptions that have been authored based on the verified treatment line, or which have been the source for creating the unverified treatment line"
  // relatedStatement 0..* Reference "Medication-related statements from patients, pharmacists, or other HCPs, that are related to the verified treatment line or are the source for creating the unverified treatment line"
  // relatedDispensation 0..* Reference "Related dispensations that are NOT related to existing prescriptions/requests/statements. Allowing this is very implemenation-specific."
  // relatedAdministration 0..* Reference "Related administrations that are NOT related to existing prescriptions/requests/statements. This might be relevant for hospital/home nursing use cases." 

* prescriptionAdditional 0..* Class "Type of medication statement (for example, drug classification like ATC, where meds would be administered, legal category of the medication.)" "Ravimiskeemi rea retseptiga seotud info."
  * courseOfTherapyType 0..* CD "Type of medication statement (for example, drug classification like ATC, where meds would be administered, legal category of the medication.)" "pidev | fikseeritud | vajadusel | muutuv | ühekordne |"
  * prescriptionCategory 0..* CD "Type of medication statement (for example, drug classification like ATC, where meds would be administered, legal category of the medication.)." "tavaretsept | narkootilise ravimi retsept | meditsiiniseadme retsept"
  * repeatCategory 0..* CD "Prescriptions to repeat" "1-kordne | 2-kordne | 3-kordne | 6-kordne"
  * unauthorizedMedication 0..1 Reference(UnauthorizedMedication) "Requesting permit for unauthorized medication." "Müügiloata ravimi taotlus"
  * reimbursement 0..1 Class "Reimbursement for this medication." "Soodusravimid"
    * reimbursementRate 0..1 CD "Reimbursement rate" "Soodustuste määrad"
    * reimbursementReason 0..1 CD "Reimbursement reason" "Soodusravimite loetelule vastav tingimus"
  * medicationLeft 0..* INT "How much medication is on the prescription left" "Ravimi jääk ravimiskeemi real."
  * totalPrescribedAmount 0..* INT "How much in total there is medication prescribed on one Medication Request. Used for calculating the current status of how much medication is left on one Medication Statement row." "Kui palju on ravimit koguseliselt välja kirutatud - näiteks 120 tabletti. Selle pealt saab arvutada jääki. Väljakirjutatud kogus."
  * prescriptionValidityTime 0..* DT "For expressing the validity of the prescription(s) in one MedicationStatement." "Retsepti kehtivuse aeg."
  * dispensationAuthorization 0..1 CD "Defines the authorization of the prescription." "Volituse liik."
  * cancelledStatusReason 0..* CD "Reason for cancellation." "Annulleerimise põhjus. Kui retsept annulleeritakse, tuleb loendist valida põhjus."
  * substitution 0..1 Class "Whether and which type of substitution is allowed for this medication treatment line" "Ravimi asendamine ja mis põhjusel"
    * substitutionType 1..1 CD "The type of substitution that is allowed." "Asendamatuse tüüp."
    * substitutionTypeReason 0..1 CD "Coded reason for the substitution requirement" "Asendamatuse põhjus."
    * substitutionTypeReasonText 0..1 ST "Textual reason for the substitution requirement" "Tekstiliselt asendamatuse põhjus."
