Logical: PatientTJT
Title: "Patient TJT - logical model"
Description: "Basic patient data relevant for this use case"
* identifier 1..* II "An identifier for this patient." "Patsiendi identifikaator"
* name 1..* EN "Patient's name, incl first name, last name, or any other relevant name parts" "Patsiendi nimi"
* address 0..* Reference(AddressTJT) "Patsiendi aadress"
* telecom 0..* Reference(TelecomTJT) "Patsiendi kontaktandmed"  
* gender 0..1 CD "Administrative Gender - the gender that the patient is considered to have for administration and record keeping purposes." "Patsiendi sugu"
* birthDate 0..1 TS "The date of birth for the individual." "Patsiendi sünniaeg." 
* deceased 0..1 BL "Indicates if the individual is deceased or not." "Surmafakt" 
* Communication 0..* Class "A language which may be used to communicate with the patient about his or her health." "Patsiendi eelistatud suhtluskeel."
  * language 0..1 CD "The language which can be used to communicate with the patient about his or her health" "Keel, mida patsiend kasutab suhtluseks"
* contactPerson 0..* Reference "A contact party for the patient" "Patsiendi kontaktandmed"
* generalPractitioner 0..* Reference(PractitionerTJT) "Patient's nominated primary care provider."