Logical: PrescriptionTJT
Title: "PrescriptionTJT - logical model"
Description: "Prescription from prescription center"
* identifier 1..* II "An identifier for this prescription" "Retsepti identifikaator. Retsepti number."
* status 1..1 CD "A code representing the status of prescription active, on-hold, ended, stopped, completed, cancelled, entered-in-error, draft, unknown." "Retsepti staatus."
* lockStatus 0..* BL "When pharmacy locks the prescription for ordering unauthorized medication for patient. True - prescription is locked for certain pharmacy. False - prescription is not locked." "Broneering retseptil. Kasutatakse juhul kui on tegemist müügiloata ravimi retseptiga, mis on saanud positiivse otsuse ning ootab apteegis tellitavat ravimit."
* reason 1..1 CD "Reason or indication for ordering the medication." "Retsepti koostamise põhjus ehk diagnoos"
* note 0..1 ST "Extra information about the prescription that could not be conveyed by the other attributes." "Lisainformatsioon retsepti kohta"
* courseOfTherapyType 0..* CD "Type of therapy" "Ravikuuri tüüp, näiteks  pidev, fikseeritud, vajadusel, muutuv, ühekordne "
* prescriptionCategory 0..* CD "Category of prescription." "Retsepti liik, näiteks tavaretsept, narkootilise ravimi retsept, meditsiiniseadme retsept."
* repeatCategory 0..* CD "Prescriptions to repeat" "Retsepti kordsus, näiteks 1-kordne, 2-kordne, 3-kordne, 6-kordne." 
* unauthorizedMedicationRequest 0..1 Reference(UnauthorizedMedication) "Requesting usage permit for unauthorized medication." "Müügiloata ravimi taotlus."
* prescribedAmount 0..1 Class "How much medication prescribed on prescription." "Väljakirjutatud ravimi kogus retseptil."
  * prescribedAmountPackage 0..1 INT "The number of medication packages." "Preparaadi pakendite kogus ja ühik, mitu pakenit välja kirjutati."
  * prescibedAmountTotal 0..1 INT "How much medication prescribed in total on prescription."Pakendipõhise ravimi korral ühe pakendi sisalduse kirjeldus, näiteks 40 tabletti pakendis on 40 tk), toimeainepõhise retsepti korral määratud kogu ravimi hulk, näiteks kui toimeaine sisaldus on 200mg, siis kümnekordse annuse jaoks 2000 mg"
* prescriptionValidityTime 0..* DT "For expressing the validity of the prescription(s)." "Retsepti kehtivuse aeg."
* prescriptionAuthorization 0..* CD "Defines the authorization of the prescription." "Retsepti volituse liik, näiteks avalik, privaatne, volitatud."
* cancelledPrescription 0..1 Class " Cancellation of prescription." "Retsepti annuleerimine."
  * cancelledStatusReason 0..* CD "Reason for cancellation." "Annulleerimise põhjus. Kui retsept annulleeritakse, tuleb loendist valida põhjus."
  * cancelledTime 0..* DT "Time of cancellation." "Annuleerimise aeg kuupäevaliselt."
* substitution 0..1 Class "Whether and which type of substitution is allowed for this medication" "Ravimi asendamatus ja põhjus."
  * substitutionType 1..1 CD "The type of substitution that is allowed." "Asendamatuse tüüp."
  * substitutionTypeReason 0..1 CD "Coded reason for the substitution requirement" "Asendamatuse põhjus."
  * substitutionTypeReasonText 0..1 ST "Textual reason for the substitution requirement" "Tekstiliselt asendamatuse põhjus."
* medication 1..1 Reference(MedicationTJT) "Medicinal product for which the prescription refers to." "Ravim, mis on retseptiga seotud."
* practitioner 1..1 Reference(PractitionerTJT) "Practitioner who is creating prescription" "Tervishoiutöötaja, kes koostas retsepti."
* organisation 1..1 Reference "Organisation connected to practitioner and prescription." "Organisatsioon, kelle tervishoiutöötaja retsepti koostas."
* dosageInstructions 0..* Reference(DosagingTJT) "Instructions about requested administration of the product" "Annustamisjuhis"
* patient 1..1 Reference(PatientTJT) "Patient" "Patsient"
* reimbursement 1..1 Class "For representation of the reimbursement rate and reason of prescription medicine." "Retsepti soodustus ja põhjus."
  * reimbursementRate 1..1 CD "Reimbursement of medication." "Retsepti soodusmäär. Retseptikeskuse loendist Soodusmäärad, näiteks 0, 50, 75, 90, 100 protsenti."
  * reimbursementReason 1..1 ST "Reason of the reimbursement rate." "Meditsiinilised tingimused, soodustuse määra põhjus."
  * reimbursementParameters 1..1 Class "Insurance response." "Mis kindlustus on patsiendil."
    * reimbursementEu 0..1 BL "EU insurance." "Patsiendil on EU ravikindlustus."
    * reimbursementOldAgeRetirement 0..1 BL "Old age pension." "Vanaduspension."
    * reimbursementIncapacityForWork 0..1 BL "Pension for incapacity for work." "Töövõimetuspension."
    * reimbursementEstonian 0..1 BL "Estonian insurance." "Eesti ravikindlustus."
// siit on veel puudu andmeelemente 
